Fix missing build dependencies; `make` not found
Fix the missing build dependencies, `make` command not found, by instead
installing a "buildpack" Debian Docker image maintained by Heroku, which
should contain the build-essentials development tools and more. This
image will be useful for this project and others in future; either way
it should have CMake install at the very least and resolve the following
error message:

```
$ make
/bin/bash: line 52: make: command not found
ERROR: Job failed: exit code 1
```