Fix failing test in Gitlab CI runner
Add a macro to only include the fix for BSD missing `fmemopen` library
for Apple OS, and require the regular `stdio.h` library.

This should resolve the following error message:
```
Makefile:35: recipe for target 'lib/fmemopen-funopen.o' failed
make: *** [lib/fmemopen-funopen.o] Error 1
ERROR: Job failed: exit code 1
```