Fix missing `sudo` command in Docker container
Resolve the following error message:

```
$ sudo apt-get install check
/bin/bash: line 48: sudo: command not found
ERROR: Job failed: exit code 1
```