Fix? Gitlab CI runner error message during tests
Attempt to failing tests within the Gitlab CI runner, which is now
apparently failing, despite it working in the pass, still working
locally and surrounding tests that execute very similar tests are still
working, so I am unsure why it is failing now.

```
$ make test
gcc -c -o test.o test.c -g -Wall
gcc -c -o src/robot.o src/robot.c -g -Wall
gcc -c -o src/robot_test.o src/robot_test.c -g -Wall
gcc -c -o src/test_helpers.o src/test_helpers.c -g -Wall
gcc -c -o src/robot_test_helpers.o src/robot_test_helpers.c -g -Wall
gcc -c -o lib/hash_table_simple.o lib/hash_table_simple.c -g -Wall
lib/hash_table_simple.c: In function 'hash_index':
lib/hash_table_simple.c:16:13: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     int i = (int) key % h->size;
             ^
gcc -c -o lib/hash_table_f2a.o lib/hash_table_f2a.c -g -Wall
gcc -c -o lib/hash_table.o lib/hash_table.c -g -Wall
gcc -c -o lib/prime.o lib/prime.c -g -Wall
gcc -c -o lib/hash_table_simple_test.o lib/hash_table_simple_test.c -g -Wall
gcc -c -o lib/hash_table_f2a_test.o lib/hash_table_f2a_test.c -g -Wall
gcc -c -o lib/hash_table_test.o lib/hash_table_test.c -g -Wall
gcc -c -o lib/prime_test.o lib/prime_test.c -g -Wall
gcc  -I/usr/local/lib/include/ -o bin/test test.o src/robot.o src/robot_test.o src/test_helpers.o src/robot_test_helpers.o lib/hash_table_simple.o lib/hash_table_f2a.o lib/hash_table.o lib/prime.o lib/hash_table_simple_test.o lib/hash_table_f2a_test.o lib/hash_table_test.o lib/prime_test.o -lm -lcheck && \
./bin/test
Running suite(s): Robot
 Hash Table simple
 Hash Table F2A
 Hash Table
 Prime
91%: Checks: 48, Failures: 4, Errors: 0
src/robot_test.c:30:P:Core:robot_test_robot_new:0: Passed
src/robot_test.c:20:P:Core:robot_test_robot_report:0: Passed
src/robot_test.c:41:P:Core:robot_test_robot_left:0: Passed
src/robot_test.c:52:F:Core:robot_test_robot_left_from_WEST:0: Assertion 'subject->facing == "SOUTH"' failed: subject->facing == "SOUT", "SOUTH" == "SOUTH"
src/robot_test.c:63:P:Core:robot_test_robot_left_from_SOUTH:0: Passed
src/robot_test.c:74:F:Core:robot_test_robot_left_from_EAST:0: Assertion 'subject->facing == "NORTH"' failed: subject->facing == "NORT", "NORTH" == "NORTH"
src/robot_test.c:85:P:Core:robot_test_robot_right:0: Passed
src/robot_test.c:96:F:Core:robot_test_robot_right_from_EAST:0: Assertion 'subject->facing == "SOUTH"' failed: subject->facing == "SOUT", "SOUTH" == "SOUTH"
src/robot_test.c:107:P:Core:robot_test_robot_right_from_SOUTH:0: Passed
src/robot_test.c:118:F:Core:robot_test_robot_right_from_WEST:0: Assertion 'subject->facing == "NORTH"' failed: subject->facing == "NORT", "NORTH" == "NORTH"
src/robot_test.c:129:P:Core:robot_test_robot_move:0: Passed
src/robot_test.c:151:P:Core:robot_test_robot_move_WEST:0: Passed
src/robot_test.c:140:P:Core:robot_test_robot_move_EAST:0: Passed
src/robot_test.c:162:P:Core:robot_test_robot_move_SOUTH:0: Passed
src/robot_test.c:173:P:Core:robot_test_robot_move_does_not_fall_off_table_at_00SOUTH:0: Passed
src/robot_test.c:184:P:Core:robot_test_robot_move_does_not_fall_off_table_at_00WEST:0: Passed
src/robot_test.c:195:P:Core:robot_test_robot_move_does_not_fall_off_table_at_04WEST:0: Passed
src/robot_test.c:206:P:Core:robot_test_robot_move_does_not_fall_off_table_at_04NORTH:0: Passed
src/robot_test.c:217:P:Core:robot_test_robot_move_does_not_fall_off_table_at_44NORTH:0: Passed
src/robot_test.c:228:P:Core:robot_test_robot_move_does_not_fall_off_table_at_44EAST:0: Passed
src/robot_test.c:239:P:Core:robot_test_robot_move_does_not_fall_off_table_at_40EAST:0: Passed
src/robot_test.c:250:P:Core:robot_test_robot_move_does_not_fall_off_table_at_40SOUTH:0: Passed
src/robot_test.c:261:P:Core:robot_test_robot_place:0: Passed
src/robot_test.c:272:P:Core:robot_test_robot_place_at_13EAST:0: Passed
src/robot_test.c:283:P:Core:robot_test_robot_exec_REPORT:0: Passed
src/robot_test.c:294:P:Core:robot_test_robot_exec_PLACE:0: Passed
src/robot_test.c:305:P:Core:robot_test_robot_exec_MOVE:0: Passed
src/robot_test.c:316:P:Core:robot_test_robot_exec_LEFT:0: Passed
src/robot_test.c:327:P:Core:robot_test_robot_exec_RIGHT:0: Passed
src/robot_test.c:338:P:Core:robot_test_robot_exec_UNKNOWN:0: Passed
src/robot_test.c:347:P:Toy Robot:toy_robot_test_run_with_example_a:0: Passed
src/robot_test.c:356:P:Toy Robot:toy_robot_test_run_with_example_b:0: Passed
src/robot_test.c:365:P:Toy Robot:toy_robot_test_run_with_example_c:0: Passed
src/robot_test.c:377:P:Toy Robot:toy_robot_test_process:0: Passed
src/robot_test.c:392:P:Toy Robot:toy_robot_test_process_complex:0: Passed
lib/hash_table_simple_test.c:10:P:Core:hash_table_simple_test_hash_new:0: Passed
lib/hash_table_simple_test.c:18:P:Core:hash_table_simple_test_hash_insert:0: Passed
lib/hash_table_simple_test.c:28:P:Core:hash_table_simple_test_hash_multiple_inserts:0: Passed
lib/hash_table_simple_test.c:37:P:Core:hash_table_simple_test_hash_lookup_unknown_key_returns_null:0: Passed
lib/hash_table_f2a_test.c:28:P:Core:hash_table_test_hash_new_from_two_arrays:0: Passed
lib/hash_table_test.c:12:P:Core:hash_table_test_hash_new:0: Passed
lib/hash_table_test.c:27:P:Core:hash_table_test_hash_insert:0: Passed
lib/hash_table_test.c:38:P:Core:hash_table_test_hash_search:0: Passed
lib/hash_table_test.c:53:P:Core:hash_table_test_hash_delete:0: Passed
lib/hash_table_test.c:70:P:Core:hash_table_test_hash_update_on_insert:0: Passed
lib/prime_test.c:8:P:Core:prime_test_is_prime:0: Passed
lib/prime_test.c:15:P:Core:prime_test_is_not_prime:0: Passed
lib/prime_test.c:22:P:Core:prime_test_next_prime:0: Passed
Makefile:54: recipe for target 'test' failed
make: *** [test] Error 1
ERROR: Job failed: exit code 1

```