Fix missing package check by updating package list
Resolve the following error message within Gitlab CI docker container:

```
$ apt-get install -y check
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package check
ERROR: Job failed: exit code 1
```