Fix failing `make` in Debian build environment
Fix failing `make` in Debian build environment, due to an old version of
`check` library being present in the Apt-get package management and
failing to find require C Real-Time library, with the "Fix" being to
install from source, which requires the current `before_script` in the
Gitlab config script now.

```
$ make test
gcc -c -o src/robot.o src/robot.c -g -Wall
gcc -c -o src/robot_test.o src/robot_test.c -g -Wall
gcc  -I/usr/local/lib/include/ -o bin/test src/robot.o src/robot_test.o src/test_helpers.c src/robot_test_helpers.c -lm -lcheck && \
./bin/test
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check.o): In function `check_get_clockid':
(.text+0xab3): undefined reference to `timer_create'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check.o): In function `check_get_clockid':
(.text+0xad5): undefined reference to `timer_delete'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_pack.o): In function `ppack':
(.text+0x526): undefined reference to `__pthread_register_cancel'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_pack.o): In function `ppack':
(.text+0x570): undefined reference to `__pthread_unregister_cancel'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function `srunner_run':
(.text+0xa92): undefined reference to `timer_create'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function `srunner_run':
(.text+0xae0): undefined reference to `timer_settime'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function `srunner_run':
(.text+0xb0a): undefined reference to `timer_delete'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x5f4): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6bf): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6d4): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x6ef): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'test' failed
make: *** [test] Error 1
ERROR: Job failed: exit code 1
```

== Notes:
- Fix substitution error in Makefile for `*.cpp` files with `*.c` files

- Update String assertion with Integer assertion, with String substring
  to avoid garbage EOF characters being read in from capturing `stdout`

== References:
- [Releases · libcheck/check]
  (https://github.com/libcheck/check/releases)

- [Linux QuickTip: Downloading and Un\-tarring in One Step]
  (https://www.howtogeek.com/howto/uncategorized/linux-quicktip-downloading-and-un-tarring-in-one-step/)

- [Using unit testing framework for C Check \- Stack Overflow]
  (https://stackoverflow.com/questions/3482715/using-unit-testing-framework-for-c-check)

- [linux \- What libraries need to be linked for timer\_create,
  timer\_settime and other timer related functions \- Stack Overflow]
  (https://stackoverflow.com/questions/259784/what-libraries-need-to-be-linked-for-timer-create-timer-settime-and-other-timer)

- [library/buildpack\-deps \- Docker Hub]
  (https://hub.docker.com/_/buildpack-deps/)